# -*- coding: utf-8 -*-
"""Sending email with python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PGcQH8G8ad0pezDDBWV367DvT4YOzjxe
"""

import smtplib
# Creates SMTP session
smtp = smtplib.SMTP('smtp.gmail.com', 587)
# Start TLS for security
smtp.starttls()
# Authentication
smtp.login("convcsc2025project@gmail.com", "omyu xsxt ryrh uxbp")
# Message to be sent
message = "test"
# Sending the mail
smtp.sendmail("convcsc2025project@gmail.com", "emailyouwanttosendto@gmail.com", message)
# Print to show process has been completed
print("Mail Sent")
# Terminating the session
smtp.quit()
